// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUnit.IntegrationTestSample;

#nullable disable

namespace TUnit.IntegrationTestSample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250605235538_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");
#pragma warning restore 612, 618
        }
    }
}
